    version: "3.3"
    services:
      spark-master:
        image: ${IMAGE_VERSION}
        ports:
          - "9091:8080"
          - "7077:7077"
          - "8888:8888" # jupyter
        volumes:
          - ./apps:/home/developer/pyspark-apps
          - ./data:/opt/spark-data
          - ./jars:/home/developer/jars
        environment:
          - SPARK_LOCAL_IP=spark-master
          - SPARK_WORKLOAD=master
          - SPARK_WORKER_CORES=2
          - SPARK_WORKER_MEMORY=1G
          - SPARK_DRIVER_MEMORY=1G
          - SPARK_EXECUTOR_MEMORY=2G
    
      spark-worker-a:
        image: ${IMAGE_VERSION}
        ports:
          - "9092:8080"
          - "7000:7000"
        depends_on:
          - spark-master
        environment:
          - SPARK_MASTER=spark://spark-master:7077
          - SPARK_WORKER_CORES=2
          - SPARK_WORKER_MEMORY=2G
          - SPARK_DRIVER_MEMORY=2G
          - SPARK_EXECUTOR_MEMORY=2G
          - SPARK_WORKLOAD=worker
          - SPARK_LOCAL_IP=spark-worker-a
        volumes:
          - ./apps:/home/developer/pyspark-apps
          - ./data:/opt/spark-data
          - ./jars:/home/developer/jars
    
      spark-worker-b:
        image: ${IMAGE_VERSION}
        ports:
          - "9093:8080"
          - "7001:7000"
        depends_on:
          - spark-master
        environment:
          - SPARK_MASTER=spark://spark-master:7077
          - SPARK_WORKER_CORES=2
          - SPARK_WORKER_MEMORY=2G
          - SPARK_DRIVER_MEMORY=2G
          - SPARK_EXECUTOR_MEMORY=2G
          - SPARK_WORKLOAD=worker
          - SPARK_LOCAL_IP=spark-worker-b
        volumes:
          - ./apps:/home/developer/pyspark-apps
          - ./data:/opt/spark-data
          - ./jars:/home/developer/jars
            
